"""
repositories/merchant_publication_repository.py
------------------------------------------------
Isolated repository for merchant publication permissions.

Safety rules for this module:
- Uses existing table: user_permissions
- Creates no new tables
- Changes no existing files
- Stores channel access and publish cadence as permission keys

Permission key format used here:
- merchant                                   -> base merchant access
- merchant.publish.hourly                    -> publish every full hour only
- merchant.publish.channel.<channel_key>     -> allowed target channel

channel_key is a normalized channel identifier generated by normalize_channel_key().
"""

from __future__ import annotations

import logging
import re
import sqlite3

from database.database import get_connection

logger = logging.getLogger(__name__)

MERCHANT_BASE_PERMISSION = "merchant"
MERCHANT_HOURLY_PERMISSION = "merchant.publish.hourly"
MERCHANT_CHANNEL_PREFIX = "merchant.publish.channel."


def normalize_channel_key(raw: str) -> str:
    """
    Normalize a channel identifier to a safe permission suffix.

    Examples:
    - "https://t.me/my_channel" -> "my_channel"
    - "@My-Channel"            -> "my_channel"
    - "  my channel  "         -> "my_channel"
    """
    text = (raw or "").strip().lower()
    text = re.sub(r"^https?://t\.me/", "", text)
    text = text.lstrip("@")
    text = text.replace("/", "_")
    text = re.sub(r"[^a-z0-9_]+", "_", text)
    text = re.sub(r"_+", "_", text).strip("_")
    return text


def _channel_permission_key(channel_key: str) -> str:
    key = normalize_channel_key(channel_key)
    if not key:
        return ""
    return f"{MERCHANT_CHANNEL_PREFIX}{key}"


def list_merchant_ids() -> list[int]:
    """Return all users with base merchant access."""
    try:
        with get_connection() as conn:
            rows = conn.execute(
                """
                SELECT telegram_id
                FROM user_permissions
                WHERE permission = ?
                ORDER BY granted_at ASC
                """,
                (MERCHANT_BASE_PERMISSION,),
            ).fetchall()
        return [int(r[0]) for r in rows if r and r[0] is not None]
    except sqlite3.Error as exc:
        logger.error("list_merchant_ids failed: %s", exc)
        return []


def merchant_has_hourly_publish(telegram_id: int) -> bool:
    """Check whether merchant is restricted to hourly publish cadence."""
    try:
        with get_connection() as conn:
            row = conn.execute(
                """
                SELECT 1
                FROM user_permissions
                WHERE telegram_id = ? AND permission = ?
                LIMIT 1
                """,
                (telegram_id, MERCHANT_HOURLY_PERMISSION),
            ).fetchone()
        return row is not None
    except sqlite3.Error as exc:
        logger.error("merchant_has_hourly_publish(%s) failed: %s", telegram_id, exc)
        return False


def set_merchant_hourly_publish(
    telegram_id: int,
    enabled: bool,
    granted_by: int | None = None,
) -> bool:
    """Enable or disable hourly publish permission for one merchant."""
    try:
        with get_connection() as conn:
            if enabled:
                conn.execute(
                    """
                    INSERT OR IGNORE INTO user_permissions
                        (telegram_id, permission, granted_by)
                    VALUES (?, ?, ?)
                    """,
                    (telegram_id, MERCHANT_HOURLY_PERMISSION, granted_by),
                )
            else:
                conn.execute(
                    """
                    DELETE FROM user_permissions
                    WHERE telegram_id = ? AND permission = ?
                    """,
                    (telegram_id, MERCHANT_HOURLY_PERMISSION),
                )
            conn.commit()
        return True
    except sqlite3.Error as exc:
        logger.error("set_merchant_hourly_publish(%s, %s) failed: %s", telegram_id, enabled, exc)
        return False


def list_merchant_allowed_channels(telegram_id: int) -> list[str]:
    """Return normalized channel keys that merchant is allowed to publish to."""
    try:
        with get_connection() as conn:
            rows = conn.execute(
                """
                SELECT permission
                FROM user_permissions
                WHERE telegram_id = ?
                  AND permission LIKE ?
                ORDER BY permission ASC
                """,
                (telegram_id, f"{MERCHANT_CHANNEL_PREFIX}%"),
            ).fetchall()
        channels: list[str] = []
        for row in rows:
            permission = str(row[0] or "")
            if not permission.startswith(MERCHANT_CHANNEL_PREFIX):
                continue
            channel_key = permission[len(MERCHANT_CHANNEL_PREFIX) :]
            if channel_key:
                channels.append(channel_key)
        return channels
    except sqlite3.Error as exc:
        logger.error("list_merchant_allowed_channels(%s) failed: %s", telegram_id, exc)
        return []


def grant_merchant_channel_access(
    telegram_id: int,
    channel_key: str,
    granted_by: int | None = None,
) -> bool:
    """Grant channel publish access to a merchant using permission key storage."""
    permission = _channel_permission_key(channel_key)
    if not permission:
        return False
    try:
        with get_connection() as conn:
            conn.execute(
                """
                INSERT OR IGNORE INTO user_permissions
                    (telegram_id, permission, granted_by)
                VALUES (?, ?, ?)
                """,
                (telegram_id, permission, granted_by),
            )
            conn.commit()
        return True
    except sqlite3.Error as exc:
        logger.error("grant_merchant_channel_access(%s, %s) failed: %s", telegram_id, channel_key, exc)
        return False


def revoke_merchant_channel_access(telegram_id: int, channel_key: str) -> bool:
    """Revoke channel publish access from a merchant."""
    permission = _channel_permission_key(channel_key)
    if not permission:
        return False
    try:
        with get_connection() as conn:
            conn.execute(
                """
                DELETE FROM user_permissions
                WHERE telegram_id = ? AND permission = ?
                """,
                (telegram_id, permission),
            )
            conn.commit()
        return True
    except sqlite3.Error as exc:
        logger.error("revoke_merchant_channel_access(%s, %s) failed: %s", telegram_id, channel_key, exc)
        return False


def merchant_can_publish_to_channel(telegram_id: int, channel_key: str) -> bool:
    """Check whether a merchant has access to a specific channel."""
    permission = _channel_permission_key(channel_key)
    if not permission:
        return False
    try:
        with get_connection() as conn:
            row = conn.execute(
                """
                SELECT 1
                FROM user_permissions
                WHERE telegram_id = ? AND permission = ?
                LIMIT 1
                """,
                (telegram_id, permission),
            ).fetchone()
        return row is not None
    except sqlite3.Error as exc:
        logger.error("merchant_can_publish_to_channel(%s, %s) failed: %s", telegram_id, channel_key, exc)
        return False
